#!/bin/sh

DEBROOT=Debian

CHKDEP=`which zeda-chkdep`

if [ "${CHKDEP}" = "" ]; then
    echo "ZEDA not correctly installed."
    exit 1
fi

DEPSTR=`grep DEPENDENCY config | sed 's/DEPENDENCY=//' | sed 's/\"//' | sed 's/\"//'`

PROJNAME=`grep PROJNAME= config | sed 's/PROJNAME=//' | sed 's/_/-/'`
VERSION=`grep VERSION config | sed 's/VERSION=//'`-debian1
USERNAME=`git config --list | grep user.name | sed 's/user.name=//'`
USEREMAIL=`git config --list | grep user.email | sed 's/user.email=//'`
DESCRIPTION=`head -n 1 README.md`
URL=`git config --get remote.origin.url|sed 's/:/\//' | sed 's/git@/https:\/\//'`
ARCH=`dpkg --print-architecture`
if [ "${DEPSTR}" != "" ]; then
    DEP=`${CHKDEP} ${DEPSTR} -deb`
else
    DEP=
fi

DEBDIR=${DEBROOT}/DEBIAN
BINDIR=${DEBROOT}/usr/bin
INCLUDEDIR=${DEBROOT}/usr/include
LIBDIR=${DEBROOT}/usr/lib
DOCDIR=${DEBROOT}/usr/share/doc/${PROJNAME}

MAKEDIR="mkdir -m 755 -p"

${MAKEDIR} ${DEBDIR}
${MAKEDIR} ${BINDIR}
${MAKEDIR} ${INCLUDEDIR}
${MAKEDIR} ${LIBDIR}
${MAKEDIR} ${DOCDIR}

cp -r lib/*.so ${LIBDIR}
cp -r include/* ${INCLUDEDIR}
install -m 755 tools/* ${BINDIR}; rm ${BINDIR}/makefile ${BINDIR}/config.tools
ls app/*.c 2> /dev/null | xargs -I{} basename {} .c | xargs -I{} install -m 755 app/{} ${BINDIR}

cat << EOF > ${DEBDIR}/control
Package: ${PROJNAME}-dev
Version: ${VERSION}
Maintainer: ${USERNAME} <${USEREMAIL}>
Homepage: ${URL}
Architecture: ${ARCH}
Section: contrib/libdevel
Priority: extra
Depends: ${DEP}
Description: ${DESCRIPTION}
EOF

git log --pretty="${PROJNAME} %n%n  * %s%n%N%n -- %cn <%ce> %cd%n" --decorate-refs=tag |gzip > ${DOCDIR}/ChangeLog.gz
cp COPYING ${DOCDIR}

fakeroot dpkg-deb --build ${DEBROOT} .

rm -rf ${DEBROOT}

exit 0
