#!/bin/sh

test "$1" || exit 0

DEPLIST=$1
RETVAL=0

while [ "${DEPLIST}" ]; do
  lib=${DEPLIST%%=*}
  DEPLIST=${DEPLIST#*=}
  rqrver=${DEPLIST%%;*}
  NEXTDEPLIST=${DEPLIST#*;}
  if [ "${NEXTDEPLIST}" = "${DEPLIST}" ]; then
    DEPLIST=""
  else
    DEPLIST=${NEXTDEPLIST}
  fi

  rqrmsg="lib${lib}: required version ${rqrver} /"
  if [ ! `which ${lib}-config` ]; then
    echo ${rqrmsg} " not installed"
    continue
  fi
  curver=`${lib}-config -v`
  msg="${rqrmsg} installed version ${curver}"

  rqrvermjr=`echo ${rqrver} | cut -d. -f 1`
  rqrvermdl=`echo ${rqrver} | cut -d. -f 2`
  rqrvermnr=`echo ${rqrver} | cut -d. -f 3`
  curvermjr=`echo ${curver} | cut -d. -f 1`
  curvermdl=`echo ${curver} | cut -d. -f 2`
  curvermnr=`echo ${curver} | cut -d. -f 3`
  if [ ${curvermjr} -gt ${rqrvermjr} ]; then
    echo ${msg} ": OK"
  else
    if [ ${curvermjr} -eq ${rqrvermjr} ]; then
      if [ ${curvermdl} -gt ${rqrvermdl} ]; then
        echo ${msg} ": OK"
      else
        if [ ${curvermdl} -eq ${rqrvermdl} -a ${curvermnr} -ge ${rqrvermnr} ]; then
          echo ${msg} ": OK"
        else
          echo ${msg} ": need update"
          RETVAL=1
        fi
      fi
    fi
  fi
done

exit ${RETVAL}
